import type { Metadata } from "next";
import "./globals.css";
import MUIThemeProvider from "@/providers/ThemeProvider";
import { GlobalLayoutProvider } from "@/providers/GlobalLayoutProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MUIThemeProvider>
          <GlobalLayoutProvider>{children}</GlobalLayoutProvider>
        </MUIThemeProvider>
      </body>
    </html>
  );
}
